In [1]:
import numpy as np

In [12]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [13]:
b.ndim

2

In [14]:
b.shape

(2, 4)

In [16]:
b.dtype

dtype('int32')

In [21]:
a = np.array([5,6.0,7], dtype='int16')

In [22]:
a.dtype

dtype('int16')

In [23]:
a.itemsize

2

In [24]:
b.itemsize

4

In [25]:
a.nbytes

6

In [27]:
a = np.array([[10,21,22,2,8,9,12],[12,1,2,4,9,6,5]])

In [28]:
print (a)

[[10 21 22  2  8  9 12]
 [12  1  2  4  9  6  5]]


In [29]:
a[0,3]

2

In [31]:
a[1,4]

9

In [32]:
a[0,-1]

12

In [33]:
a[1,-4]

4

In [34]:
print(a)

[[10 21 22  2  8  9 12]
 [12  1  2  4  9  6  5]]


In [35]:
a[0]

array([10, 21, 22,  2,  8,  9, 12])

In [36]:
print(a[0])

[10 21 22  2  8  9 12]


In [37]:
print(a[0,:])

[10 21 22  2  8  9 12]


In [39]:
print(a[:,0])

[10 12]


In [40]:
a[0,2] = 12

In [41]:
print(a[0])

[10 21 12  2  8  9 12]


In [42]:
a[:,3] = 3

In [43]:
print(a)

[[10 21 12  3  8  9 12]
 [12  1  2  3  9  6  5]]


In [46]:
a[:,3] = [1,2]

In [47]:
print(a)

[[10 21 12  1  8  9 12]
 [12  1  2  2  9  6  5]]


In [52]:
b = np.array([[[3,4],[6,5]],[[1,5],[9,8]]])
print(b)

[[[3 4]
  [6 5]]

 [[1 5]
  [9 8]]]


In [54]:
np.zeros(4)

array([0., 0., 0., 0.])

In [55]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
np.zeros((4,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [58]:
np.ones(4)

array([1., 1., 1., 1.])

In [59]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [62]:
np.full((3,3),3,dtype = 'float32')

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

In [63]:
a

array([[10, 21, 12,  1,  8,  9, 12],
       [12,  1,  2,  2,  9,  6,  5]])

In [64]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [65]:
np.random.rand(4,2)

array([[0.6870159 , 0.89538371],
       [0.82970963, 0.8479456 ],
       [0.37885872, 0.92015098],
       [0.6003013 , 0.43240086]])

In [69]:
np.random.random_sample(a.shape)

array([[2.80260584e-01, 8.73484637e-01, 8.92692099e-01, 5.11705291e-01,
        4.05607573e-01, 3.04947624e-01, 1.05654067e-01],
       [4.20001866e-04, 8.19544929e-01, 6.43454857e-01, 1.56213603e-01,
        9.98425947e-01, 4.86499861e-01, 7.05494376e-01]])

In [70]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [71]:
arr = np.array([[11,12,5]])
a1 = np.repeat(arr, 3, axis =0)
print(a1)

[[11 12  5]
 [11 12  5]
 [11 12  5]]


In [72]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [73]:
a +5

array([6, 7, 8, 9])

In [74]:
a-3

array([-2, -1,  0,  1])

In [75]:
a*3

array([ 3,  6,  9, 12])

In [76]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [77]:
a//3

array([0, 0, 1, 1], dtype=int32)

In [78]:
b = np.array([5,6,7,8])

In [79]:
a+b

array([ 6,  8, 10, 12])

In [81]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [82]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [83]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [86]:
a = np.full((3,4),5)
b = np.full((4,5),4)
print(a)
print(b)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [87]:
np.matmul(a,b)

array([[80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80]])

In [88]:
c = np.identity(5)

In [89]:
np.linalg.det(c)

1.0

In [90]:
s = np.array([[1,2,3],[4,5,6]])

In [91]:
s

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
np.min(s, axis = 0)

array([1, 2, 3])

In [93]:
np.min(s, axis = 1)

array([1, 4])

In [94]:
np.max(s)

6

In [95]:
np.sum(s)

21

In [96]:
np.sum(s, axis =1)

array([ 6, 15])

In [98]:
b1 = np.array([[2,4,6,8],[1,3,5,7]])
b1

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [99]:
a1 = b1.reshape((4,2))

In [100]:
print(a1)

[[2 4]
 [6 8]
 [1 3]
 [5 7]]


In [101]:
a1 = b1.resshape((2,3))

AttributeError: 'numpy.ndarray' object has no attribute 'resshape'

In [103]:
#veritcal stacking
v1 = np.array([2,4,6,8])
v2 = np.array([1,3,4,5])

In [104]:
np.vstack([v1,v2])

array([[2, 4, 6, 8],
       [1, 3, 4, 5]])

In [105]:
np.hstack([v1,v2])

array([2, 4, 6, 8, 1, 3, 4, 5])

In [106]:
#import data from a file

In [107]:
#google colab
Data = np.genfromtxt()

TypeError: genfromtxt() missing 1 required positional argument: 'fname'

In [108]:
#boolean MAsking adn advanced indexing

In [109]:
data >5

NameError: name 'data' is not defined

In [110]:
data ==2

NameError: name 'data' is not defined

In [111]:
a = np.array([10,20,30,40,50,60,70,80,90,100])

In [112]:
a[[2,5,8]]

array([30, 60, 90])

In [113]:
np.any(a>50, axis = 0)

True

In [117]:
age = "1515"
print ("I am , age," )

I am , age,


In [122]:
print ("I am ,{}".format(age) )

I am ,1515


In [123]:
print ("I am ,{age}" )

I am ,{age}


In [124]:
#inverse string
print(name[::-1])

NameError: name 'name' is not defined

In [125]:
#Gap in a array
print(name[1:20:2])

NameError: name 'name' is not defined

In [128]:
name = "My name is thor  a"
print(name.index("a"))

4


In [129]:
name = "My name is thor  a"
print(name.index("thor"))

11


In [130]:
name = "My name is thor  a"
print(name.replace("thor","a"))

My name is a  a


In [131]:
from math import *
print(round(5.4))

5


In [134]:
from math import *
print(ceil(5.4))

6


In [135]:
from math import *
print(sqrt(5.4))

2.32379000772445


In [136]:
input1 = input()
print(input1)

2
2


In [137]:
input1 = input()
print("your name is: "+ input1)

juan
your name is: juan


In [138]:
#26 list
avengers = ["Iron Man","Captina America","Thor","Hulk","Black widow", "Hawkeye"]
print(avengers)

['Iron Man', 'Captina America', 'Thor', 'Hulk', 'Black widow', 'Hawkeye']


In [142]:
avengers = ["Iron Man","Captina America","Thor","Hulk","Black widow", "Hawkeye",1,2,3,4,5,6,True,False]
print(avengers)

['Iron Man', 'Captina America', 'Thor', 'Hulk', 'Black widow', 'Hawkeye', 1, 2, 3, 4, 5, 6, True, False]


In [143]:
avengers = ["Iron Man","Captina America","Thor","Hulk","Black widow", "Hawkeye",1,2,3,4,5,6,True,False]
print(avengers[0])

Iron Man


In [144]:
avengers = ["Iron Man","Captina America","Thor","Hulk","Black widow", "Hawkeye",1,2,3,4,5,6,True,False]
print(avengers[0:3])

['Iron Man', 'Captina America', 'Thor']


In [146]:
avengers = ["Iron Man","Captina America","Thor","Hulk","Black widow", "Hawkeye",1,2,3,4,5,6,True,False]
print(avengers[0][0])

I


In [148]:
avengers = ["Iron Man","Captina America","Thor","Hulk","Black widow", "Hawkeye",1,2,3,4,5,6,True,False]
numbers = [1,2,3,4,5,6]
avengers.extend(numbers)

In [149]:
avengers

['Iron Man',
 'Captina America',
 'Thor',
 'Hulk',
 'Black widow',
 'Hawkeye',
 1,
 2,
 3,
 4,
 5,
 6,
 True,
 False,
 1,
 2,
 3,
 4,
 5,
 6]

In [151]:
avengers = ["Iron Man","Captina America","Thor","Hulk","Black widow", "Hawkeye",1,2,3,4,5,6,True,False]
numbers = [1,2,3,4,5,6]
avengers.append("Black Panther")
avengers

['Iron Man',
 'Captina America',
 'Thor',
 'Hulk',
 'Black widow',
 'Hawkeye',
 1,
 2,
 3,
 4,
 5,
 6,
 True,
 False,
 'Black Panther']

In [153]:
avengers = ["Iron Man","Captina America","Thor","Hulk","Black widow", "Hawkeye",1,2,3,4,5,6,True,False]
numbers = [1,2,3,4,5,6]
avengers.insert(2,"Black Panther")
avengers

['Iron Man',
 'Captina America',
 'Black Panther',
 'Thor',
 'Hulk',
 'Black widow',
 'Hawkeye',
 1,
 2,
 3,
 4,
 5,
 6,
 True,
 False]

In [155]:
avengers = ["Iron Man","Captina America","Thor","Hulk","Black widow", "Hawkeye",1,2,3,4,5,6,True,False]
numbers = [1,2,3,4,5,6]
avengers.remove("Thor")
avengers

['Iron Man',
 'Captina America',
 'Hulk',
 'Black widow',
 'Hawkeye',
 1,
 2,
 3,
 4,
 5,
 6,
 True,
 False]

In [156]:
avengers = ["Iron Man","Captina America","Thor","Hulk","Black widow", "Hawkeye",1,2,3,4,5,6,True,False]
avengers.pop()
avengers

['Iron Man',
 'Captina America',
 'Thor',
 'Hulk',
 'Black widow',
 'Hawkeye',
 1,
 2,
 3,
 4,
 5,
 6,
 True]

In [157]:
print(avengers.index("Thor"))


2


In [158]:
print(avengers.count("Thor"))


1


In [162]:
avengers = ["Iron Man","Captina America","Thor","Hulk","Black widow", "Hawkeye"]
avengers.sort(reverse = True)
avengers

['Thor', 'Iron Man', 'Hulk', 'Hawkeye', 'Captina America', 'Black widow']

In [170]:
#tuple are not mutable, list can be mutable
new_tuple = (2,3)
list = [(1,2),(2,5),(6,8)]
list [0] = (6,9)
print(list)

[(6, 9), (2, 5), (6, 8)]


In [176]:
#only the key not index
list = ["a","b","c"]

dic1 = {
"alpha":"a",
"beta" : "b",
"Tiger" : "c"
}
print(dic1["alpha"])
print(dic1)
print(dic1["beta"])

a
{'alpha': 'a', 'beta': 'b', 'Tiger': 'c'}
b


In [179]:
def new_fun(a,b):
    print('hello1')
    c = a+b
    print(c)
new_fun(2,6)
print('hello2')

hello1
8
hello2


In [188]:
# se termina con return la función
def cube(num):
    c = num*num*num
    return c 
print(cube(3))

27


In [4]:
#nested loops

numbers =[
    [2,4,6],
    [6,8,9],
    [3,5,7]
]

print(numbers[0])

for  i in numbers:
    for j in i:
        print(j)

[2, 4, 6]
2
4
6
6
8
9
3
5
7


In [11]:
try:
    
    number = int(input("Pleased enter a number:"))
    print(number)
    
except:
    print("Please enter a valid number")

Pleased enter a number:3
3


In [6]:
#reading files